linux: &linux
   os: linux
   dist: bionic
   language: python
   python: "3.7"
   services:
     - docker

matrix:
  include:
    - stage: installer
      <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7-centos6 ARCH=x86_64

import: bincrafters/templates:.ci/travis-macos-installer.yml@master
